version: 2
updates:
  # Enable version updates for Cargo (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "vouchrs/maintainers"
    assignees:
      - "vouchrs/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
        - "*"
        exclude-patterns:
        - "*dev*"
        - "*test*"
      development-dependencies:
        patterns:
        - "*dev*"
        - "*test*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "vouchrs/maintainers"
    assignees:
      - "vouchrs/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "vouchrs/maintainers"
    assignees:
      - "vouchrs/maintainers"
    commit-message:
      prefix: "docker"
      include: "scope"
